### ISSUE TITLE
File date

### ISSUE THREAD

**Issue by pbruck** [d-EScape/filehub-rpwd03-sdbackup#1]
Hi
at first I want to thank you so much for this great script and function upgrade.
I own this device since 6 years but ever missed the possibility to make incremental backups and to make backups without using additional device like smartphone.
I use it for SD card backups out in the field at Backcountry and backpack trips.
A few days ago I found your script and installed and tested it.
It works great and I am absolutely excited about the new possibilities.
So I immediately bought an second device for testing OpenWRT and some other things.

But one thing I find not so perfect.
The files will be copied and created at the target USB disc with the date and time of the copy time.
Is it possible to copy them and keep the origin creation time and date at which the photos and videos are taken?

Can I, or you, modify something in the script to change this?

How you can help me with this.

And, once again, thank you so much for this great work and für sharing it.
Piet

**Comment by d-EScape** [comment]
Hi Piet,

Glad you are still getting some use out of this script after all these years. I share the script as-is and am not actively maintaining it. An iPad or iPhone has been my on the road backup solution for some years now.
